In [2]:
 import numpy as np

In [3]:
#2. crear un vector de tamaño 10
ceros = np.zeros(10)
ceros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
#3.
ceros_uno = np.zeros(10)
ceros_uno[5] = 1
ceros_uno

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

In [5]:
#4. 
vector_50 = np.arange(50)
print(f"{vector_50}\n\n")
print(vector_50[::-1])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]


[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


In [6]:
#5.
vector_8 = np.arange(9)
vector_8.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [9]:
#6.
a = np.arange(10)
np.indices(a)

array([], shape=(10, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9), dtype=int32)

In [10]:
#7.
matriz_identidad = np.eye(3)
matriz_identidad

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
#8.
matriz_random = arreglo_random = np.random.randint(
    0, 
    20,
    27 
)
matriz_random.reshape(3,3,3)

array([[[ 8,  0,  7],
        [18, 12, 19],
        [18,  2, 14]],

       [[ 5, 18, 15],
        [ 1, 19, 16],
        [ 2,  0,  4]],

       [[16,  1, 16],
        [17,  0, 17],
        [13, 10, 17]]])

In [12]:
#9 
matriz_10 = arreglo_random = np.random.randint(
    0, 
    100,
    100 
)

print(matriz_10.reshape(10,10))
print(f"\nmax: {np.max(matriz_10)}")
print(f"min: {np.min(matriz_10)}")

[[45 21 65 92  1 48 99 89 86 21]
 [98 57 65 49 27 72 19 61 12 16]
 [19 16 70 38 42 78 85  9 54 48]
 [94  4 53 92 93 10 92 87  8 49]
 [82 30 81 50 16 77 36 44 84 41]
 [88 85 36 59 50 88 58 53 49 88]
 [86 84 60 62 47 53 90 37 22 59]
 [16 66 75 65 61 11 29 81 76 19]
 [85 11 60 98 41 57 13 32 27 96]
 [15  6 44 55 46 84 30 71 82  2]]

max: 99
min: 1


In [ ]:
#10

from PIL import Image
photo = Image.open('minio.jpg') #your image
photo = photo.convert('RGB')

width = photo.size[0] #define W and H
height = photo.size[1]

for y in range(0, height): #each pixel has coordinates
    row = ""
    for x in range(0, width):

        RGB = photo.getpixel((x,y))
        R,G,B = RGB  #now you can use the RGB value
        print(RGB)

In [24]:
#11
import pandas as pd
mylist = list('abcdefghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist,myarr))

#Serie de lista
serie_a = pd.Series(mylist) 
print(f"Serie Lista\n{serie_a}")
#Serie de arreglo
serie_b = pd.Series(myarr)
print(f"Serie Arreglo\n{serie_b}")
#Serie de diccionario
serie_c = pd.Series(mydict)
print(f"Serie Diccionario\n{serie_c}")

Serie Lista
0     a
1     b
2     c
3     d
4     e
5     f
6     g
7     h
8     i
9     j
10    k
11    l
12    m
13    n
14    o
15    p
16    q
17    r
18    s
19    t
20    u
21    v
22    w
23    x
24    y
25    z
dtype: object
Serie Arreglo
0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
11    11
12    12
13    13
14    14
15    15
16    16
17    17
18    18
19    19
20    20
21    21
22    22
23    23
24    24
25    25
dtype: int32
Serie Diccionario
a     0
b     1
c     2
d     3
e     4
f     5
g     6
h     7
i     8
j     9
k    10
l    11
m    12
n    13
o    14
p    15
q    16
r    17
s    18
t    19
u    20
v    21
w    22
x    23
y    24
z    25
dtype: int64


In [31]:
#12

mylist = list('abcdefghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist,myarr))


ser = pd.Series(mydict)
df = pd.DataFrame(ser,index=mylist)
print(df)

    0
a   0
b   1
c   2
d   3
e   4
f   5
g   6
h   7
i   8
j   9
k  10
l  11
m  12
n  13
o  14
p  15
q  16
r  17
s  18
t  19
u  20
v  21
w  22
x  23
y  24
z  25


In [35]:
#13. 
ser1 = pd.Series(list('abcdefghijklmnopqrstuvwxyz'))
ser2 = pd.Series(np.arange(26))
df = pd.DataFrame(ser1)
df[1] = ser2

print(df)

    0   1
0   a   0
1   b   1
2   c   2
3   d   3
4   e   4
5   f   5
6   g   6
7   h   7
8   i   8
9   j   9
10  k  10
11  l  11
12  m  12
13  n  13
14  o  14
15  p  15
16  q  16
17  r  17
18  s  18
19  t  19
20  u  20
21  v  21
22  w  22
23  x  23
24  y  24
25  z  25


In [43]:
#19.
ser = pd.Series(list('abcdefghijklmnopqrstuvwxyz'))
pos = [0, 4, 8, 14, 20]

print(ser[pos[0]])
print(ser[pos[1]])
print(ser[pos[2]])
print(ser[pos[3]])
print(ser[pos[4]])


a
e
i
o
u


In [55]:
ser1_1 = pd.Series(range(5))
ser2_2 = pd.Series(list('abcde'))

dff = pd.DataFrame({
    'A': ser1_1,
    'B': ser2_2
})

print(dff)

   A  B
0  0  a
1  1  b
2  2  c
3  3  d
4  4  e


In [40]:
#22
path ='C:\\Users\\jonat\\Documents\\GitHub\\py-vargas-nilve-jonathan-santiago\\examen\\BostonHousing.csv'
dfBH = pd.read_csv(path)

columnas = ['crim', 'zn']
dfBH = pd.read_csv(path, usecols = columnas, index_col = 'crim')
dfBH.head(10)

zn
crim         
0.00632  18.0
0.02731   0.0
0.02729   0.0
0.03237   0.0
0.06905   0.0
0.02985   0.0
0.08829  12.5
0.14455  12.5
0.21124  12.5
0.17004  12.5