In [2]:
#pip install numpy
#numpy para notas matematicas
#numpy acepta lista y tuplas

import numpy as np

In [3]:
#tipos de listas y arreglos conocidos
#se puede crear numpy con listas y arreglos
print(type([1,2,3]))
print(type((1,2,3)))

print(type(np.array([1,2,3])))
print(type(np.array((1,2,3))))     

<class 'list'>
<class 'tuple'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [5]:
#llenar una matriz con ceros

np.zeros([1]) #arreglo de un elemento
np.zeros([5]) #arreglo de 5 elemento

array([0., 0., 0., 0., 0.])

In [6]:
np.zeros((1))

array([0.])

In [7]:
np.zeros([5,7]) #matriz 5x7

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [8]:
np.zeros([5,7,8])

array([[[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.,

In [9]:
np.zeros((5,7,8))

array([[[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.,

In [11]:
np.ones([5,6]) #matriz llenas de uno

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [12]:
#matriz identidad
np.eye((4))

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [14]:
#imprime secuencia de numeros. imprime el numero de elementos que se le especifica
np.arange(11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
np.arange(4,20) #[4, 20[

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [17]:
#con un solo numero negativo no sirve
#funciona con  un negativo y un positivo
np.arange(-2)
np.arange(-12,1)

array([-12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0])

In [21]:
#ir de un  numero a otro numero pero con saltos
arreglo_pares = np.arange(0,20,2) #saltos de 2
np.arange(-12,12,0.5)

array([-12. , -11.5, -11. , -10.5, -10. ,  -9.5,  -9. ,  -8.5,  -8. ,
        -7.5,  -7. ,  -6.5,  -6. ,  -5.5,  -5. ,  -4.5,  -4. ,  -3.5,
        -3. ,  -2.5,  -2. ,  -1.5,  -1. ,  -0.5,   0. ,   0.5,   1. ,
         1.5,   2. ,   2.5,   3. ,   3.5,   4. ,   4.5,   5. ,   5.5,
         6. ,   6.5,   7. ,   7.5,   8. ,   8.5,   9. ,   9.5,  10. ,
        10.5,  11. ,  11.5])

In [26]:
#imprimir la dimension
print(arreglo_pares.size)
print(len(arreglo_pares))

arreglo_tres_dim = np.zeros((2,3,4))
print(arreglo_tres_dim.shape) #imprimir las dims de una matriz de 3 dims

10
10
(2, 3, 4)


In [43]:
print(arreglo_pares) #tengo 10 elementos
arreglo_pares.reshape(5,2) #dos numeros multiplicados me de el numero de elementos 5x2 = 10.... Redimensionar matrices

[ 0  2  4  6  8 10 12 14 16 18]


array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [29]:
arreglo_pares.reshape(2,5)

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [41]:
arreglo_comb = np.arange(24)
#combinaciones
"""
print(arreglo_comb.reshape(12,2))
print(arreglo_comb.reshape(2,12))
print(arreglo_comb.reshape(6,4))
print(arreglo_comb.reshape(4,6))
print(arreglo_comb.reshape(8,3))
print(arreglo_comb.reshape(3,8))

"""
np.arange(12,24)

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [46]:
a = np.array([10,10,10])
b = np.array([5,5,5])

In [47]:
#suma
a + b

array([15, 15, 15])

In [48]:
#resta
a - b

array([5, 5, 5])

In [49]:
#multi
a * b 

array([50, 50, 50])

In [51]:
#divisiones 
a / b

array([2., 2., 2.])

In [74]:
# arreglo de 3 dimensiones

c = np.arange(2,21,2).reshape(5,2,1)
#d = np.arange(4,22,0.5).reshape(15,2,2)
d = np.arange(4,9,0.5).reshape(5,2,1)
d


array([[[4. ],
        [4.5]],

       [[5. ],
        [5.5]],

       [[6. ],
        [6.5]],

       [[7. ],
        [7.5]],

       [[8. ],
        [8.5]]])

In [75]:
 c + d

array([[[ 6. ],
        [ 8.5]],

       [[11. ],
        [13.5]],

       [[16. ],
        [18.5]],

       [[21. ],
        [23.5]],

       [[26. ],
        [28.5]]])

In [63]:
#mod

a % b
a * 10

array([100, 100, 100])

In [68]:
#multiplicar
print(a * 10)
#sumar
print(a + 7)
#restar
print (a - 2 )
#dividir
print (a / 2)

[100 100 100]
[17 17 17]
[8 8 8]
[5. 5. 5.]


In [76]:
arreglo_muestra = np.arange(20).reshape(5,2,2)

In [77]:
arreglo_muestra

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19]]])

In [80]:
#obtener los mayores a 5
resp = arreglo_muestra > 5

resp

array([[[False, False],
        [False, False]],

       [[False, False],
        [ True,  True]],

       [[ True,  True],
        [ True,  True]],

       [[ True,  True],
        [ True,  True]],

       [[ True,  True],
        [ True,  True]]])

In [128]:
#mayores a 5 y menores 12
resp = arreglo_muestra[((arreglo_muestra > 5) & (arreglo_muestra < 12 ))] #& (arreglo_muestra % 2 )


#mayores a 6 menores a 14 y pares/2
resp1 = arreglo_muestra[((arreglo_muestra > 6) & (arreglo_muestra < 14 ) & (arreglo_muestra % 2 == 0))] #& (arreglo_muestra % 2 )

print(f"Respuesta 1 :{resp}")
print(f"Respuesta 2 :{resp1}")



Respuesta 1 :[ 6  7  8  9 10 11]
Respuesta 2 :[ 8 10 12]


In [136]:
A = np.arange(4).reshape(2,2)

B = np.arange(4,8).reshape(2,2)


#producto punto 
np.dot(A,B) #1 forma
A.dot(B) # 2 forma


array([[ 6,  7],
       [26, 31]])

In [171]:
#

arreglo_doce = np.arange(12)
arreglo_doce 

#suma de todo el arreglo
arreglo_doce.sum()

#cual es el minimo ()
arreglo_doce.min()

#cual es el maximo()
arreglo_doce.max()


arreglo_doce.reshape(3,2,2)


array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [173]:
arreglo_doce.reshape(3,2,2).sum(axis = 0)

array([[12, 15],
       [18, 21]])

In [167]:
arreglo_doce.reshape(3,5,1,2).sum(axis = 1)

array([[[ 20,  25]],

       [[ 70,  75]],

       [[120, 125]]])

In [174]:
arreglo_doce.reshape(3,2,2).sum(axis = 2)

array([[ 1,  5],
       [ 9, 13],
       [17, 21]])