In [4]:
import numpy as np

In [5]:
arreglo_cero_diez = np.arange(11)
arreglo_cero_diez

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
#elevar al cudrado los numeros. en modo python
arreglo_cero_diez = np.arange(11) ** 2 
arreglo_cero_diez

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [7]:
#como cortar y sacar posiciones del arreglo

#SLICING
arreglo_cero_diez[5]

25

In [8]:
arreglo_cero_diez [0:7]

array([ 0,  1,  4,  9, 16, 25, 36], dtype=int32)

In [9]:
arreglo_cero_diez[-6:-1]

array([25, 36, 49, 64, 81], dtype=int32)

In [11]:
arreglo_cero_diez[2:-3]

array([ 4,  9, 16, 25, 36, 49], dtype=int32)

In [10]:
arreglo_cero_diez[2:]

array([  4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [13]:
arreglo_cero_diez[:-3]

array([ 0,  1,  4,  9, 16, 25, 36, 49], dtype=int32)

In [14]:
arreglo_cero_diez[:]

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [13]:
#obtener los numeros pares.. saltos de 2
arreglo_cero_diez[::2]

array([  0,   4,  16,  36,  64, 100], dtype=int32)

In [14]:
#elementos de atras para adelante
arreglo_cero_diez[::-1]

array([100,  81,  64,  49,  36,  25,  16,   9,   4,   1,   0], dtype=int32)

In [15]:
arreglo_cero_diez [::-2]

array([100,  64,  36,  16,   4,   0], dtype=int32)